#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
NAME=zha_start

start_service() {
	procd_open_instance
  sh /usr/bin/zigbeeserviceStart.sh &
	procd_close_instance
}

stop() {
  sh /usr/bin/zigbeeserviceStop.sh
}

#/sbin/zigbeeservice_test &
#/bin/discover_gateway &

