#! /bin/sh
#==========
while : 
do 
#echo "Current DIR is " $PWD 
stillRunning=$(ps |grep "zigbeeservice_test" |grep -v "grep") 
if [ "$stillRunning" ] ; then 
echo "TWS service was already started by another way" 
echo "Kill it and then startup by this shell, other wise this shell will loop out this message annoyingly" 
#kill -9 $pidof $PWD/loader 
else 
echo "TWS service was not started" 
echo "Starting service ..." 
#$PWD/loader 
zigbeeservice_test &
echo "TWS service was exited!" 
fi 
sleep 15
ifconfig > /tmp/is_ap_connected.txt
ubus call zha get_coordinfo > /tmp/ieee.txt
done
