#!/bin/sh

uci delete dhcp.@dnsmasq[0]
uci add dhcp dnsmasq
echo "uci set dhcp.@dnsmasq[0]=dnsmasq"
uci set dhcp.@dnsmasq[0]=dnsmasq
echo "uci set dhcp.@dnsmasq[0].domainneeded=1"
uci set dhcp.@dnsmasq[0].domainneeded=1
echo "uci set dhcp.@dnsmasq[0].boguspriv=1"
uci set dhcp.@dnsmasq[0].boguspriv=1
echo "uci set dhcp.@dnsmasq[0].filterwin2k=0"
uci set dhcp.@dnsmasq[0].filterwin2k=0
echo "uci set dhcp.@dnsmasq[0].localise_queries=1"
uci set dhcp.@dnsmasq[0].localise_queries=1
echo "uci set dhcp.@dnsmasq[0].rebind_protection=1"
uci set dhcp.@dnsmasq[0].rebind_protection=1
echo "uci set dhcp.@dnsmasq[0].rebind_localhost=1"
uci set dhcp.@dnsmasq[0].rebind_localhost=1
echo "uci set dhcp.@dnsmasq[0].local=/lan/"
uci set dhcp.@dnsmasq[0].local=/lan/
echo "uci set dhcp.@dnsmasq[0].domain=lan"
uci set dhcp.@dnsmasq[0].domain=lan
echo "uci set dhcp.@dnsmasq[0].expandhosts=1"
uci set dhcp.@dnsmasq[0].expandhosts=1
echo "uci set dhcp.@dnsmasq[0].nonegcache=0"
uci set dhcp.@dnsmasq[0].nonegcache=0
echo "uci set dhcp.@dnsmasq[0].authoritative=1"
uci set dhcp.@dnsmasq[0].authoritative=1
echo "uci set dhcp.@dnsmasq[0].readethers=1"
uci set dhcp.@dnsmasq[0].readethers=1
echo "uci set dhcp.@dnsmasq[0].leasefile=/tmp/dhcp.leases"
uci set dhcp.@dnsmasq[0].leasefile=/tmp/dhcp.leases
echo "uci set dhcp.@dnsmasq[0].resolvfile=/tmp/resolv.conf.auto"
uci set dhcp.@dnsmasq[0].resolvfile=/tmp/resolv.conf.auto

uci delete dhcp.lan
#uci add dhcp lan
echo "uci set dhcp.lan=dhcp"
uci set dhcp.lan=dhcp
echo "uci set dhcp.lan.interface=lan"
uci set dhcp.lan.interface=lan
echo "uci set dhcp.lan.start=100"
uci set dhcp.lan.start=100
echo "uci set dhcp.lan.limit=150"
uci set dhcp.lan.limit=150
echo "uci set dhcp.lan.leasetime=12h"
uci set dhcp.lan.leasetime=12h
echo "uci set dhcp.lan.dhcpv6=server"
uci set dhcp.lan.dhcpv6=server
echo "uci set dhcp.lan.ra=server"
uci set dhcp.lan.ra=server

uci delete dhcp.wan
#uci add dhcp wan
echo "uci set dhcp.wan=dhcp"
uci set dhcp.wan=dhcp
echo "uci set dhcp.wan.interface=wan"
uci set dhcp.wan.interface=wan


uci delete dhcp.odhcpd
#uci add dhcp odhcpd
echo "uci set dhcp.odhcpd=odhcpd"
uci set dhcp.odhcpd=odhcpd
echo "uci set dhcp.odhcpd.maindhcp=0"
uci set dhcp.odhcpd.maindhcp=0
echo "uci set dhcp.odhcpd.leasefile=/tmp/hosts/odhcpd"
uci set dhcp.odhcpd.leasefile=/tmp/hosts/odhcpd
echo "uci set dhcp.odhcpd.leasetrigger=/usr/sbin/odhcpd-update"
uci set dhcp.odhcpd.leasetrigger=/usr/sbin/odhcpd-update

echo "dhcp set over"

uci delete dropbear.@dropbear[0]
uci add dropbear dropbear
echo "uci set dropbear.@dropbear[0]=dropbear"
uci set dropbear.@dropbear[0]=dropbear
echo "uci set dropbear.@dropbear[0].PasswordAuth=on"
uci set dropbear.@dropbear[0].PasswordAuth=on
echo "uci set dropbear.@dropbear[0].RootPasswordAuth=on"
uci set dropbear.@dropbear[0].RootPasswordAuth=on
echo "uci set dropbear.@dropbear[0].Port=22"
uci set dropbear.@dropbear[0].Port=22

echo "dropbear set over"

uci delete firewall.@defaults[0]
uci add firewall defaults
echo "uci set firewall.@defaults[0]=defaults"
uci set firewall.@defaults[0]=defaults
echo "uci set firewall.@defaults[0].syn_flood=1"
uci set firewall.@defaults[0].syn_flood=1
echo "uci set firewall.@defaults[0].input=ACCEPT"
uci set firewall.@defaults[0].input=ACCEPT
echo "uci set firewall.@defaults[0].output=ACCEPT"
uci set firewall.@defaults[0].output=ACCEPT
echo "uci set firewall.@defaults[0].forward=REJECT"
uci set firewall.@defaults[0].forward=REJECT

uci delete firewall.@zone[1]
uci delete firewall.@zone[0]
uci add firewall zone
uci add firewall zone
echo "uci set firewall.@zone[0]=zone"
uci set firewall.@zone[0]=zone
echo "uci set firewall.@zone[0].name=lan"
uci set firewall.@zone[0].name=lan
echo "uci set firewall.@zone[0].network=lan"
uci set firewall.@zone[0].network=lan
echo "uci set firewall.@zone[0].input=ACCEPT"
uci set firewall.@zone[0].input=ACCEPT
echo "uci set firewall.@zone[0].output=ACCEPT"
uci set firewall.@zone[0].output=ACCEPT
echo "uci set firewall.@zone[0].forward=ACCEPT"
uci set firewall.@zone[0].forward=ACCEPT
echo "uci set firewall.@zone[1]=zone"
uci set firewall.@zone[1]=zone
echo "uci set firewall.@zone[1].name=wan"
uci set firewall.@zone[1].name=wan
echo "uci add_list firewall.@zone[1].network=wan"
uci add_list firewall.@zone[1].network=wan
echo "uci add_list firewall.@zone[1].network=wan6"
uci add_list firewall.@zone[1].network=wan6
echo "uci set firewall.@zone[1].input=ACCEPT"
uci set firewall.@zone[1].input=ACCEPT
echo "uci set firewall.@zone[1].output=ACCEPT"
uci set firewall.@zone[1].output=ACCEPT
echo "uci set firewall.@zone[1].forward=REJECT"
uci set firewall.@zone[1].forward=REJECT
echo "uci set firewall.@zone[1].masq=1"
uci set firewall.@zone[1].masq=1
echo "uci set firewall.@zone[1].mtu_fix=1"
uci set firewall.@zone[1].mtu_fix=1

uci delete firewall.@forwarding[0]
uci add firewall forwarding
echo "uci set firewall.@forwarding[0]=forwarding"
uci set firewall.@forwarding[0]=forwarding
echo "uci set firewall.@forwarding[0].src=lan"
uci set firewall.@forwarding[0].src=lan
echo "uci set firewall.@forwarding[0].dest=wan"
uci set firewall.@forwarding[0].dest=wan

uci delete firewall.@rule[4]
uci delete firewall.@rule[3]
uci delete firewall.@rule[2]
uci delete firewall.@rule[1]
uci delete firewall.@rule[0]
uci add firewall rule
uci add firewall rule
uci add firewall rule
uci add firewall rule
uci add firewall rule
echo "uci set firewall.@rule[0]=rule"
uci set firewall.@rule[0]=rule
echo "uci set firewall.@rule[0].name=Allow-DHCP-Renew"
uci set firewall.@rule[0].name=Allow-DHCP-Renew
echo "uci set firewall.@rule[0].src=wan"
uci set firewall.@rule[0].src=wan
echo "uci set firewall.@rule[0].proto=udp"
uci set firewall.@rule[0].proto=udp
echo "uci set firewall.@rule[0].dest_port=68"
uci set firewall.@rule[0].dest_port=68
echo "uci set firewall.@rule[0].target=ACCEPT"
uci set firewall.@rule[0].target=ACCEPT
echo "uci set firewall.@rule[0].family=ipv4"
uci set firewall.@rule[0].family=ipv4
echo "uci set firewall.@rule[1]=rule"
uci set firewall.@rule[1]=rule
echo "uci set firewall.@rule[1].name=Allow-Ping"
uci set firewall.@rule[1].name=Allow-Ping
echo "uci set firewall.@rule[1].src=wan"
uci set firewall.@rule[1].src=wan
echo "uci set firewall.@rule[1].proto=icmp"
uci set firewall.@rule[1].proto=icmp
echo "uci set firewall.@rule[1].icmp_type=echo-request"
uci set firewall.@rule[1].icmp_type=echo-request
echo "uci set firewall.@rule[1].family=ipv4"
uci set firewall.@rule[1].family=ipv4
echo "uci set firewall.@rule[1].target=ACCEPT"
uci set firewall.@rule[1].target=ACCEPT
echo "uci set firewall.@rule[2]=rule"
uci set firewall.@rule[2]=rule
echo "uci set firewall.@rule[2].name=Allow-DHCPv6"
uci set firewall.@rule[2].name=Allow-DHCPv6
echo "uci set firewall.@rule[2].src=wan"
uci set firewall.@rule[2].src=wan
echo "uci set firewall.@rule[2].proto=udp"
uci set firewall.@rule[2].proto=udp
echo "uci set firewall.@rule[2].src_ip=fe80::/10"
uci set firewall.@rule[2].src_ip=fe80::/10
echo "uci set firewall.@rule[2].src_port=547"
uci set firewall.@rule[2].src_port=547
echo "uci set firewall.@rule[2].dest_ip=fe80::/10"
uci set firewall.@rule[2].dest_ip=fe80::/10
echo "uci set firewall.@rule[2].dest_port=546"
uci set firewall.@rule[2].dest_port=546
echo "uci set firewall.@rule[2].family=ipv6"
uci set firewall.@rule[2].family=ipv6
echo "uci set firewall.@rule[2].target=ACCEPT"
uci set firewall.@rule[2].target=ACCEPT
echo "uci set firewall.@rule[3]=rule"
uci set firewall.@rule[3]=rule
echo "uci set firewall.@rule[3].name=Allow-ICMPv6-Input"
uci set firewall.@rule[3].name=Allow-ICMPv6-Input
echo "uci set firewall.@rule[3].src=wan"
uci set firewall.@rule[3].src=wan
echo "uci set firewall.@rule[3].proto=icmp"
uci set firewall.@rule[3].proto=icmp
echo "uci add_list firewall.@rule[3].icmp_type=echo-request"
uci add_list firewall.@rule[3].icmp_type=echo-request
echo "uci add_list firewall.@rule[3].icmp_type=echo-reply"
uci add_list firewall.@rule[3].icmp_type=echo-reply
echo "uci add_list firewall.@rule[3].icmp_type=destination-unreachable"
uci add_list firewall.@rule[3].icmp_type=destination-unreachable
echo "uci add_list firewall.@rule[3].icmp_type=packet-too-big"
uci add_list firewall.@rule[3].icmp_type=packet-too-big
echo "uci add_list firewall.@rule[3].icmp_type=time-exceeded"
uci add_list firewall.@rule[3].icmp_type=time-exceeded
echo "uci add_list firewall.@rule[3].icmp_type=bad-header"
uci add_list firewall.@rule[3].icmp_type=bad-header
echo "uci add_list firewall.@rule[3].icmp_type=unknown-header-type"
uci add_list firewall.@rule[3].icmp_type=unknown-header-type
echo "uci add_list firewall.@rule[3].icmp_type=router-solicitation "
uci add_list firewall.@rule[3].icmp_type=router-solicitation
echo "uci add_list firewall.@rule[3].icmp_type=neighbour-solicitation"
uci add_list firewall.@rule[3].icmp_type=neighbour-solicitation
echo "uci add_list firewall.@rule[3].icmp_type=router-advertisement"
uci add_list firewall.@rule[3].icmp_type=router-advertisement
echo "uci add_list firewall.@rule[3].icmp_type=neighbour-advertisement"
uci add_list firewall.@rule[3].icmp_type=neighbour-advertisement
echo "uci set firewall.@rule[3].limit=1000/sec"
uci set firewall.@rule[3].limit=1000/sec
echo "uci set firewall.@rule[3].family=ipv6"
uci set firewall.@rule[3].family=ipv6
echo "uci set firewall.@rule[3].target=ACCEPT"
uci set firewall.@rule[3].target=ACCEPT
echo "uci set firewall.@rule[4]=rule"
uci set firewall.@rule[4]=rule
echo "uci set firewall.@rule[4].name=Allow-ICMPv6-Forward"
uci set firewall.@rule[4].name=Allow-ICMPv6-Forward
echo "uci set firewall.@rule[4].src=wan"
uci set firewall.@rule[4].src=wan
echo "uci set firewall.@rule[4].dest=*"
uci set firewall.@rule[4].dest=*
echo "uci set firewall.@rule[4].proto=icmp"
uci set firewall.@rule[4].proto=icmp
echo "uci add_list firewall.@rule[4].icmp_type=echo-request"
uci add_list firewall.@rule[4].icmp_type=echo-request
echo "uci add_list firewall.@rule[4].icmp_type=echo-reply"
uci add_list firewall.@rule[4].icmp_type=echo-reply
echo "uci add_list firewall.@rule[4].icmp_type=destination-unreachable"
uci add_list firewall.@rule[4].icmp_type=destination-unreachable
echo "uci add_list firewall.@rule[4].icmp_type=packet-too-big"
uci add_list firewall.@rule[4].icmp_type=packet-too-big
echo "uci add_list firewall.@rule[4].icmp_type=time-exceeded"
uci add_list firewall.@rule[4].icmp_type=time-exceeded
echo "uci add_list firewall.@rule[4].icmp_type=bad-header"
uci add_list firewall.@rule[4].icmp_type=bad-header
echo "uci add_list firewall.@rule[4].icmp_type=unknown-header-type"
uci add_list firewall.@rule[4].icmp_type=unknown-header-type
echo "uci set firewall.@rule[4].limit=1000/sec"
uci set firewall.@rule[4].limit=1000/sec
echo "uci set firewall.@rule[4].family=ipv6"
uci set firewall.@rule[4].family=ipv6
echo "uci set firewall.@rule[4].target=ACCEPT"
uci set firewall.@rule[4].target=ACCEPT

uci delete firewall.@include[0]
uci add firewall include
echo "uci set firewall.@include[0]=include"
uci set firewall.@include[0]=include
echo "uci set firewall.@include[0].path=/etc/firewall.user"
uci set firewall.@include[0].path=/etc/firewall.user

echo "firewall set over"

uci delete luci.main
#uci add luci main
echo "uci set luci.main=core"
uci set luci.main=core
echo "uci set luci.main.lang=zh_cn"
uci set luci.main.lang=zh_cn
echo "uci set luci.main.mediaurlbase=/luci-static/bootstrap"
uci set luci.main.mediaurlbase=/luci-static/bootstrap
echo "uci set luci.main.resourcebase=/luci-static/resources"
uci set luci.main.resourcebase=/luci-static/resources

uci delete luci.flash_keep
#uci add luci flash_keep
echo "uci set luci.flash_keep=extern"
uci set luci.flash_keep=extern
echo "uci set luci.flash_keep.uci=/etc/config/"
uci set luci.flash_keep.uci=/etc/config/
echo "uci set luci.flash_keep.dropbear=/etc/dropbear/"
uci set luci.flash_keep.dropbear=/etc/dropbear/
echo "uci set luci.flash_keep.openvpn=/etc/openvpn/"
uci set luci.flash_keep.openvpn=/etc/openvpn/
echo "uci set luci.flash_keep.passwd=/etc/passwd"
uci set luci.flash_keep.passwd=/etc/passwd
echo "uci set luci.flash_keep.opkg=/etc/opkg.conf"
uci set luci.flash_keep.opkg=/etc/opkg.conf
echo "uci set luci.flash_keep.firewall=/etc/firewall.user"
uci set luci.flash_keep.firewall=/etc/firewall.user
echo "uci set luci.flash_keep.uploads=/lib/uci/upload/"
uci set luci.flash_keep.uploads=/lib/uci/upload/

uci delete luci.languages
#uci add luci languages
echo "uci set luci.languages=internal"
uci set luci.languages=internal
echo "uci set luci.languages.zh_cn=Chinese"
uci set luci.languages.zh_cn=Chinese

uci delete luci.sauth
#uci add luci sauth
echo "uci set luci.sauth=internal"
uci set luci.sauth=internal
echo "uci set luci.sauth.sessionpath=/tmp/luci-sessions"
uci set luci.sauth.sessionpath=/tmp/luci-sessions
echo "uci set luci.sauth.sessiontime=3600"
uci set luci.sauth.sessiontime=3600

uci delete luci.ccache
#uci add luci ccache
echo "uci set luci.ccache=internal"
uci set luci.ccache=internal
echo "uci set luci.ccache.enable=1"
uci set luci.ccache.enable=1

uci delete luci.themes
#uci add luci themes
echo "uci set luci.themes=internal"
uci set luci.themes=internal
echo "uci set luci.themes.Bootstrap=/luci-static/bootstrap"
uci set luci.themes.Bootstrap=/luci-static/bootstrap

echo "luci set over"

uci delete network.loopback
#uci add network loopback
echo "uci set network.loopback=interface"
uci set network.loopback=interface
echo "uci set network.loopback.ifname=lo"
uci set network.loopback.ifname=lo
echo "uci set network.loopback.proto=static"
uci set network.loopback.proto=static
echo "uci set network.loopback.ipaddr=127.0.0.1"
uci set network.loopback.ipaddr=127.0.0.1
echo "uci set network.loopback.netmask=255.0.0.0"
uci set network.loopback.netmask=255.0.0.0

uci delete network.globals
#uci add network globals
echo "uci set network.globals=globals"
uci set network.globals=globals
echo "uci set network.globals.ula_prefix=fda8:4103:81a8::/48"
uci set network.globals.ula_prefix=fda8:4103:81a8::/48

uci delete network.lan
#uci add network lan
echo "uci set network.lan=interface"
uci set network.lan=interface
echo "uci set network.lan.force_link=1"
uci set network.lan.force_link=1
echo "uci set network.lan.type=bridge"
uci set network.lan.type=bridge
echo "uci set network.lan.ipaddr=192.168.100.1"
uci set network.lan.ipaddr=192.168.100.1
echo "uci set network.lan.netmask=255.255.255.0"
uci set network.lan.netmask=255.255.255.0
echo "uci set network.lan.ip6assign=60"
uci set network.lan.ip6assign=60
echo "uci set network.lan.proto=static"
uci set network.lan.proto=static

uci delete network.wan
#uci add network wan
echo "uci set network.wan=interface"
uci set network.wan=interface
echo "uci set network.wan.ifname=eth1"
uci set network.wan.ifname=eth1
echo "uci set network.wan.force_link=1"
uci set network.wan.force_link=1
echo "uci set network.wan.proto=dhcp"
uci set network.wan.proto=dhcp

echo "network set over"

uci delete rpcd.@login[0]
uci add rpcd login
echo "uci set rpcd.@login[0]=login"
uci set rpcd.@login[0]=login
echo "uci set rpcd.@login[0].username=root"
uci set rpcd.@login[0].username=root
echo "uci set rpcd.@login[0].password=$p$root"
uci set rpcd.@login[0].password=$p$root
echo "uci set rpcd.@login[0].read=*"
uci set rpcd.@login[0].read=*
echo "uci set rpcd.@login[0].write=*"
uci set rpcd.@login[0].write=*

echo "rpcd set over"

uci delete system.@system[0]
uci add system system
echo "uci set system.@system[0]=system"
uci set system.@system[0]=system
echo "uci set system.@system[0].hostname=iGateway"
uci set system.@system[0].hostname=iGateway
echo "uci set system.@system[0].zonename=Asia/Shanghai"
uci set system.@system[0].zonename=Asia/Shanghai
echo "uci set system.@system[0].timezone=CST-8"
uci set system.@system[0].timezone=CST-8

uci delete system.ntp
#uci add system ntp
echo "uci set system.ntp=timeserver"
uci set system.ntp=timeserver
echo "uci add_list system.ntp.server=0.openwrt.pool.ntp.org"
uci add_list system.ntp.server=0.openwrt.pool.ntp.org
echo "uci add_list system.ntp.server=1.openwrt.pool.ntp.org"
uci add_list system.ntp.server=1.openwrt.pool.ntp.org
echo "uci ad_list system.ntp.server=2.openwrt.pool.ntp.org"
uci add_list system.ntp.server=2.openwrt.pool.ntp.org
echo "uci add_list system.ntp.server=3.openwrt.pool.ntp.org"
uci add_list system.ntp.server=3.openwrt.pool.ntp.org
echo "uci set system.ntp.enabled=1"
uci set system.ntp.enabled=1
echo "uci set system.ntp.enable_server=0"
uci set system.ntp.enable_server=0

uci delete system.led_wlan
#uci add system led_wlan
echo "uci set system.led_wlan=led"
uci set system.led_wlan=led
echo "uci set system.led_wlan.name=WLAN"
uci set system.led_wlan.name=WLAN
echo "uci set system.led_wlan.sysfs=igateway:green:wlan"
uci set system.led_wlan.sysfs=igateway:green:wlan
echo "uci set system.led_wlan.trigger=phy0tpt"
uci set system.led_wlan.trigger=phy0tpt

echo "system set over"

uci delete ucitrack.@network[0]
uci add ucitrack network
echo "uci set ucitrack.@network[0]=network"
uci set ucitrack.@network[0]=network
echo "uci set ucitrack.@network[0].init=network"
uci set ucitrack.@network[0].init=network
echo "uci add_list ucitrack.@network[0].affects=dhcp"
uci add_list ucitrack.@network[0].affects=dhcp
echo "uci add_list ucitrack.@network[0].affects=radvd"
uci add_list ucitrack.@network[0].affects=radvd

uci delete ucitrack.@wireless[0]
uci add ucitrack wireless
echo "uci set ucitrack.@wireless[0]=wireless"
uci set ucitrack.@wireless[0]=wireless
echo "uci set ucitrack.@wireless[0].affects=network"
uci set ucitrack.@wireless[0].affects=network

uci delete ucitrack.@firewall[0]
uci add ucitrack firewall
echo "uci set ucitrack.@firewall[0]=firewall"
uci set ucitrack.@firewall[0]=firewall
echo "uci set ucitrack.@firewall[0].init=firewall"
uci set ucitrack.@firewall[0].init=firewall
echo "uci add_list ucitrack.@firewall[0].affects=luci-splash"
uci add_list ucitrack.@firewall[0].affects=luci-splash
echo "uci add_list ucitrack.@firewall[0].affects=qos"
uci add_list ucitrack.@firewall[0].affects=qos
echo "uci add_list ucitrack.@firewall[0].affects=miniupnpd"
uci add_list ucitrack.@firewall[0].affects=miniupnpd

uci delete ucitrack.@olsr[0]
uci add ucitrack olsr
echo "uci set ucitrack.@olsr[0]=olsr"
uci set ucitrack.@olsr[0]=olsr
echo "uci set ucitrack.@olsr[0].init=olsrd"
uci set ucitrack.@olsr[0].init=olsrd

uci delete ucitrack.@dhcp[0]
uci add ucitrack dhcp
echo "uci set ucitrack.@dhcp[0]=dhcp"
uci set ucitrack.@dhcp[0]=dhcp
echo "uci set ucitrack.@dhcp[0].init=dnsmasq"
uci set ucitrack.@dhcp[0].init=dnsmasq
echo "uci set ucitrack.@dhcp[0].affects=odhcpd"
uci set ucitrack.@dhcp[0].affects=odhcpd

uci delete ucitrack.@odhcpd[0]
uci add ucitrack odhcpd
echo "uci set ucitrack.@odhcpd[0]=odhcpd"
uci set ucitrack.@odhcpd[0]=odhcpd
echo "uci set ucitrack.@odhcpd[0].init=odhcpd"
uci set ucitrack.@odhcpd[0].init=odhcpd

uci delete ucitrack.@dropbear[0]
uci add ucitrack dropbear
echo "uci set ucitrack.@dropbear[0]=dropbear"
uci set ucitrack.@dropbear[0]=dropbear
echo "uci set ucitrack.@dropbear[0].init=dropbear"
uci set ucitrack.@dropbear[0].init=dropbear

uci delete ucitrack.@httpd[0]
uci add ucitrack httpd
echo "uci set ucitrack.@httpd[0]=httpd"
uci set ucitrack.@httpd[0]=httpd
echo "uci set ucitrack.@httpd[0].init=httpd"
uci set ucitrack.@httpd[0].init=httpd

uci delete ucitrack.@fstab[0]
uci add ucitrack fstab
echo "uci set ucitrack.@fstab[0]=fstab"
uci set ucitrack.@fstab[0]=fstab
echo "uci set ucitrack.@fstab[0].init=fstab"
uci set ucitrack.@fstab[0].init=fstab

uci delete ucitrack.@qos[0]
uci add ucitrack qos
echo "uci set ucitrack.@qos[0]=qos"
uci set ucitrack.@qos[0]=qos
echo "uci set ucitrack.@qos[0].init=qos"
uci set ucitrack.@qos[0].init=qos

uci delete ucitrack.@system[0]
uci add ucitrack system
echo "uci set ucitrack.@system[0]=system"
uci set ucitrack.@system[0]=system
echo "uci set ucitrack.@system[0].init=led"
uci set ucitrack.@system[0].init=led
echo "uci set ucitrack.@system[0].affects=luci_statistics"
uci set ucitrack.@system[0].affects=luci_statistics

uci delete ucitrack.@luci_splash[0]
uci add ucitrack luci_splash
echo "uci set ucitrack.@luci_splash[0]=luci_splash"
uci set ucitrack.@luci_splash[0]=luci_splash
echo "uci set ucitrack.@luci_splash[0].init=luci_splash"
uci set ucitrack.@luci_splash[0].init=luci_splash

uci delete ucitrack.@upnpd[0]
uci add ucitrack upnpd
echo "uci set ucitrack.@upnpd[0]=upnpd"
uci set ucitrack.@upnpd[0]=upnpd
echo "uci set ucitrack.@upnpd[0].init=miniupnpd"
uci set ucitrack.@upnpd[0].init=miniupnpd

uci delete ucitrack.@ntpclient[0]
uci add ucitrack ntpclient
echo "uci set ucitrack.@ntpclient[0]=ntpclient"
uci set ucitrack.@ntpclient[0]=ntpclient
echo "uci set ucitrack.@ntpclient[0].init=ntpclient"
uci set ucitrack.@ntpclient[0].init=ntpclient

uci delete ucitrack.@samba[0]
uci add ucitrack samba
echo "uci set ucitrack.@samba[0]=samba"
uci set ucitrack.@samba[0]=samba
echo "uci set ucitrack.@samba[0].init=samba"
uci set ucitrack.@samba[0].init=samba

uci delete ucitrack.@tinyproxy[0]
uci add ucitrack tinyproxy
echo "uci set ucitrack.@tinyproxy[0]=tinyproxy"
uci set ucitrack.@tinyproxy[0]=tinyproxy
echo "uci set ucitrack.@tinyproxy[0].init=tinyproxy"
uci set ucitrack.@tinyproxy[0].init=tinyproxy

uci delete ucitrack.@6relayd[0]
uci add ucitrack 6relayd
echo "uci set ucitrack.@6relayd[0]=6relayd"
uci set ucitrack.@6relayd[0]=6relayd
echo "uci set ucitrack.@6relayd[0].init=6relayd"
uci set ucitrack.@6relayd[0].init=6relayd

echo "ucitrack set over"

uci delete uhttpd.main
#uci add uhttpd main
echo "uci set uhttpd.main=uhttpd"
uci set uhttpd.main=uhttpd
echo "uci add_list uhttpd.main.listen_http=0.0.0.0:80"
uci add_list uhttpd.main.listen_http=0.0.0.0:80
echo "uci add_list uhttpd.main.listen_http=[::]:80"
uci add_list uhttpd.main.listen_http=[::]:80
echo "uci add_list uhttpd.main.listen_https=0.0.0.0:443"
uci add_list uhttpd.main.listen_https=0.0.0.0:443
echo "uci add_list uhttpd.main.listen_https=[::]:443"
uci add_list uhttpd.main.listen_https=[::]:443
echo "uci set uhttpd.main.home=/www"
uci set uhttpd.main.home=/www
echo "uci set uhttpd.main.rfc1918_filter=1"
uci set uhttpd.main.rfc1918_filter=1
echo "uci set uhttpd.main.max_requests=3"
uci set uhttpd.main.max_requests=3
echo "uci set uhttpd.main.max_connections=100"
uci set uhttpd.main.max_connections=100
echo "uci set uhttpd.main.cert=/etc/uhttpd.crt"
uci set uhttpd.main.cert=/etc/uhttpd.crt
echo "uci set uhttpd.main.key=/etc/uhttpd.key"
uci set uhttpd.main.key=/etc/uhttpd.key
echo "uci set uhttpd.main.cgi_prefix=/cgi-bin"
uci set uhttpd.main.cgi_prefix=/cgi-bin
echo "uci set uhttpd.main.script_timeout=60"
uci set uhttpd.main.script_timeout=60
echo "uci set uhttpd.main.network_timeout=30"
uci set uhttpd.main.network_timeout=30
echo "uci set uhttpd.main.http_keepalive=20"
uci set uhttpd.main.http_keepalive=20
echo "uci set uhttpd.main.tcp_keepalive=1"
uci set uhttpd.main.tcp_keepalive=1
echo "uci set uhttpd.main.ubus_prefix=/ubus"
uci set uhttpd.main.ubus_prefix=/ubus
echo "uci set uhttpd.main.no_ubusauth=1"
uci set uhttpd.main.no_ubusauth=1

uci delete uhttpd.px5g
#uci add uhttpd px5g
echo "uci set uhttpd.px5g=cert"
uci set uhttpd.px5g=cert
echo "uci set uhttpd.px5g.days=730"
uci set uhttpd.px5g.days=730
echo "uci set uhttpd.px5g.bits=1024"
uci set uhttpd.px5g.bits=1024
echo "uci set uhttpd.px5g.country=DE"
uci set uhttpd.px5g.country=DE
echo "uci set uhttpd.px5g.state=Berlin"
uci set uhttpd.px5g.state=Berlin
echo "uci set uhttpd.px5g.location=Berlin"
uci set uhttpd.px5g.location=Berlin
echo "uci set uhttpd.px5g.commonname=OpenWrt"
uci set uhttpd.px5g.commonname=OpenWrt

echo "uhttpd set over"

uci delete wireless.radio0
#uci add wireless radio0
echo "uci set wireless.radio0=wifi-device"
uci set wireless.radio0=wifi-device
echo "uci set wireless.radio0.type=mac80211"
uci set wireless.radio0.type=mac80211
echo "uci set wireless.radio0.hwmode=11g"
uci set wireless.radio0.hwmode=11g
echo "uci set wireless.radio0.path=platform/ar933x_wmac"
uci set wireless.radio0.path=platform/ar933x_wmac
echo "uci set wireless.radio0.channel=auto"
uci set wireless.radio0.channel=auto
echo "uci set wireless.radio0.txpower=30"
uci set wireless.radio0.txpower=30
echo "uci set wireless.radio0.country=US"
uci set wireless.radio0.country=US

uci delete wireless.@wifi-iface[0]
uci add wireless wifi-iface
echo "uci set wireless.@wifi-iface[0]=wifi-iface"
uci set wireless.@wifi-iface[0]=wifi-iface
echo "uci set wireless.@wifi-iface[0].device=radio0"
uci set wireless.@wifi-iface[0].device=radio0
echo "uci set wireless.@wifi-iface[0].network=lan"
uci set wireless.@wifi-iface[0].network=lan
echo "uci set wireless.@wifi-iface[0].encryption=psk2"
uci set wireless.@wifi-iface[0].encryption=psk2
echo "uci set wireless.@wifi-iface[0].key=123456789"
uci set wireless.@wifi-iface[0].key=123456789
echo "uci set wireless.@wifi-iface[0].ssid=zha-gateway_new"
uci set wireless.@wifi-iface[0].ssid=zha-gateway_new
echo "uci set wireless.@wifi-iface[0].mode=ap"
uci set wireless.@wifi-iface[0].mode=ap

echo "wireless set over"

echo "uci commit dhcp"
uci commit dhcp
echo "uci commit dropbear"
uci commit dropbear
echo "uci commit firewall"
uci commit firewall
echo "uci commit luci"
uci commit luci
echo "uci commit network"
uci commit network
echo "uci commit rpcd"
uci commit rpcd
echo "uci commit system"
uci commit system
echo "uci commit ucitrack"
uci commit ucitrack
echo "uci commit uhttpd"
uci commit uhttpd
echo "uci commit wireless"
uci commit wireless

echo "reboot..."
reboot



